"""Add content column to stories table

Revision ID: 3b07a7a04c5a
Revises: initial_migration
Create Date: 2025-01-20 14:57:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b07a7a04c5a'
down_revision = 'initial_migration'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('content', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stories', 'content')
    # ### end Alembic commands ###